#Before Docker
#spring.application.name=productservice
#spring.config.import=optional:configserver:http://localhost:8888

#After Docker
spring.application.name=productservice
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
