spring.application.name=configserver

server.port=8888

# Eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#After Docker 
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# Native Mode
spring.profiles.active=native

# Folder containing configuration files
spring.cloud.config.server.native.search-locations=classpath:/config

# Actuator
management.endpoints.web.exposure.include=*