apiVersion: apps/v1
kind: Deployment

metadata:
  name: paymentservice-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: paymentservice

  template:
    metadata:
      labels:
        app: paymentservice

    spec:
      containers:
        - name: paymentservice-container
          image: paymentservice:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8085

          env:
            - name: CONFIG_SERVER_URL
              value: http://configserver:8888

            - name: EUREKA_SERVER_URL
              value: http://discoveryserver:8761/eureka/

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092